name: data-pipeline-workflow
on:
  push:
  schedule:
    - cron: "35 0 * * *"  #run everyday at 12:35 am
  workflow_dispatch: # for manual triggers
  

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name:  Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: pip install  -r requirements.txt

    - name: Run data pipeline
      
      run: |
        python -m venv myenv   
        source myenv/bin/activate
        python data_pipeline.py

    - name: Check for changes
      id: git-check
      run: |
        git config user.name "github-actions"
        git config user.email 'github-actions@github.com'
        git add .
        if git diff --staged --quiet; then
          echo "changes=false" >> $GITHUB_ENV
        else
          echo "changes=true" >> $GITHUB_ENV
        fi
        
    - name: Commit and push if changes
      if:  ${{ env.changes == 'true' }}  # Properly reference env variable #if changes made push new data to repo
      run: |
        git commit -m "updated peak predictions"
        git push
    